export interface Dua {
  id: string;
  category: string;
  title: string;
  arabic: string;
  transliteration: string;
  translation: string;
  reference: string;
  source: string;
  benefits?: string;
  occasion?: string;
}

export const DUA_CATEGORIES = [
  { id: 'morning', name: 'Morning Adhkar', arabicName: 'أذكار الصباح', icon: '🌅', count: 12 },
  { id: 'evening', name: 'Evening Adhkar', arabicName: 'أذكار المساء', icon: '🌆', count: 12 },
  { id: 'sleep', name: 'Before Sleep', arabicName: 'قبل النوم', icon: '🌙', count: 8 },
  { id: 'wakeup', name: 'Upon Waking', arabicName: 'عند الاستيقاظ', icon: '⭐', count: 5 },
  { id: 'prayer', name: 'After Prayer', arabicName: 'بعد الصلاة', icon: '🕌', count: 10 },
  { id: 'eating', name: 'Eating & Drinking', arabicName: 'الأكل والشرب', icon: '🍽️', count: 6 },
  { id: 'travel', name: 'Travel', arabicName: 'السفر', icon: '✈️', count: 8 },
  { id: 'quran', name: 'Quranic Duas', arabicName: 'أدعية قرآنية', icon: '📖', count: 20 },
  { id: 'protection', name: 'Protection', arabicName: 'الحماية', icon: '🛡️', count: 10 },
  { id: 'forgiveness', name: 'Forgiveness', arabicName: 'الاستغفار', icon: '💚', count: 8 },
  { id: 'illness', name: 'Illness & Health', arabicName: 'المرض والصحة', icon: '🏥', count: 7 },
  { id: 'anxiety', name: 'Anxiety & Stress', arabicName: 'الهم والحزن', icon: '💙', count: 6 },
  { id: 'mosque', name: 'Entering Mosque', arabicName: 'دخول المسجد', icon: '🕌', count: 4 },
  { id: 'parents', name: 'Parents', arabicName: 'الوالدين', icon: '👨‍👩‍👦', count: 4 },
  { id: 'knowledge', name: 'Knowledge', arabicName: 'العلم', icon: '📚', count: 5 },
  { id: 'rizq', name: 'Provision & Rizq', arabicName: 'الرزق', icon: '💰', count: 5 },
  { id: 'istikhara', name: 'Istikhara', arabicName: 'صلاة الاستخارة', icon: '🤲', count: 2 },
  { id: 'ramadan', name: 'Ramadan', arabicName: 'رمضان', icon: '🌙', count: 8 },
  { id: 'hajj', name: 'Hajj & Umrah', arabicName: 'الحج والعمرة', icon: '🕋', count: 10 },
  { id: 'general', name: 'General Duas', arabicName: 'أدعية عامة', icon: '🤲', count: 15 },
];

export const DUAS: Dua[] = [
  {
    id: 'morning_1',
    category: 'morning',
    title: 'Morning Remembrance - Ayat al-Kursi',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ',
    transliteration: 'Allahu la ilaha illa huwa al-hayyul-qayyum',
    translation: 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence.',
    reference: 'Quran 2:255',
    source: 'Al-Quran al-Kareem',
    benefits: 'Reciting this in the morning and evening provides protection throughout the day',
    occasion: 'Morning',
  },
  {
    id: 'morning_2',
    category: 'morning',
    title: 'Morning Supplication - Master of Istighfar',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana abduka, wa ana ala ahdika wa wadika mastataetu, audhu bika min sharri ma sanatu, abuu laka binimatika alayya, wa abuu bidhanbee faghfir lee fa innahu la yaghfiru adh-dhunuba illa ant',
    translation: 'O Allah, You are my Lord, none has the right to be worshipped except You, You created me and I am Your servant and I abide to Your covenant and promise as best I can, I take refuge in You from the evil of which I committed. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for verily none can forgive sin except You.',
    reference: 'Sahih al-Bukhari 6306',
    source: 'Sahih al-Bukhari',
    benefits: 'Whoever recites this with conviction in the morning and dies before evening, will be among the people of Paradise',
    occasion: 'Morning - after Fajr',
  },
  {
    id: 'morning_3',
    category: 'morning',
    title: 'Morning Glorification - Surah Al-Ikhlas, Al-Falaq, An-Nas',
    arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ',
    transliteration: 'Qul huwa Allahu ahad. Allahu as-samad. Lam yalid wa lam yulad. Wa lam yakun lahu kufuwan ahad.',
    translation: 'Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born, Nor is there to Him any equivalent.',
    reference: 'Quran 112:1-4 | Abu Dawood 5082',
    source: 'Al-Quran al-Kareem',
    benefits: 'Recite three times in morning and evening - sufficient protection from everything',
    occasion: 'Morning (3 times)',
  },
  {
    id: 'morning_4',
    category: 'morning',
    title: 'Morning Remembrance - Tasbih',
    arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ',
    transliteration: 'Subhanallahi wa bihamdihi',
    translation: 'Glory be to Allah and Praise Him.',
    reference: 'Sahih al-Bukhari 6405, Sahih Muslim 2691',
    source: 'Sahih al-Bukhari & Muslim',
    benefits: 'Whoever says this 100 times in the morning and evening, no one will come with better deeds on the Day of Resurrection',
    occasion: 'Morning (100 times)',
  },
  {
    id: 'evening_1',
    category: 'evening',
    title: 'Evening Remembrance - Seeking Protection',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: 'Audhu bi kalimatillahit-tammati min sharri ma khalaq',
    translation: 'I seek refuge in the Perfect Words of Allah from the evil of what He has created.',
    reference: 'Sahih Muslim 2708',
    source: 'Sahih Muslim',
    benefits: 'Nothing will harm the one who says this three times in the evening',
    occasion: 'Evening (3 times)',
  },
  {
    id: 'sleep_1',
    category: 'sleep',
    title: 'Before Sleep - Al-Kafirun',
    arabic: 'بِسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismika Allahumma amutu wa ahya',
    translation: 'In Your name O Allah, I die and I live.',
    reference: 'Sahih al-Bukhari 6324',
    source: 'Sahih al-Bukhari',
    benefits: 'The Prophet (PBUH) used to recite this when going to sleep',
    occasion: 'Before sleeping',
  },
  {
    id: 'sleep_2',
    category: 'sleep',
    title: 'Before Sleep - Tasbeeh',
    arabic: 'سُبْحَانَ اللَّهِ ثَلَاثًا وَثَلَاثِينَ، وَالْحَمْدُ لِلَّهِ ثَلَاثًا وَثَلَاثِينَ، وَاللَّهُ أَكْبَرُ أَرْبَعًا وَثَلَاثِينَ',
    transliteration: 'SubhanAllah (33 times), Alhamdulillah (33 times), Allahu Akbar (34 times)',
    translation: 'Glory be to Allah (33 times), All praise is due to Allah (33 times), Allah is the Greatest (34 times).',
    reference: 'Sahih al-Bukhari 3705, Sahih Muslim 2727',
    source: 'Sahih al-Bukhari & Muslim',
    benefits: 'The Prophet taught this to Fatimah (RA) - better than a servant',
    occasion: 'Before sleeping',
  },
  {
    id: 'wakeup_1',
    category: 'wakeup',
    title: 'Upon Waking Up',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: 'Alhamdulillahil-ladhi ahyanabaada ma amatana wa ilayhin-nushur',
    translation: 'All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection.',
    reference: 'Sahih al-Bukhari 6312',
    source: 'Sahih al-Bukhari',
    benefits: 'First dua to recite upon waking',
    occasion: 'Upon waking up',
  },
  {
    id: 'eating_1',
    category: 'eating',
    title: 'Before Eating',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah',
    translation: 'In the name of Allah.',
    reference: 'Sahih al-Bukhari 5376, Sahih Muslim 2017',
    source: 'Sahih al-Bukhari & Muslim',
    benefits: 'The Prophet (PBUH) instructed us to say Bismillah before eating',
    occasion: 'Before eating',
  },
  {
    id: 'eating_2',
    category: 'eating',
    title: 'After Eating',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    transliteration: 'Alhamdulillahil-ladhi atamania hadha wa razaqanihi min ghayri hawlin minni wa la quwwah',
    translation: 'All praise is for Allah who fed me this and provided it for me without any might nor power from myself.',
    reference: 'Abu Dawood 4023, Tirmidhi 3458',
    source: 'Abu Dawood',
    benefits: 'His past sins will be forgiven',
    occasion: 'After eating',
  },
  {
    id: 'travel_1',
    category: 'travel',
    title: 'Dua for Travel',
    arabic: 'اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    transliteration: 'Allahu Akbar, Allahu Akbar, Allahu Akbar, Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila Rabbina lamunqalibun',
    translation: 'Allah is the Greatest (3x), How perfect He is, the One Who has placed this (transport) at our service, and we ourselves would not have been capable of that, and to our Lord is our final destination.',
    reference: 'Abu Dawood 2602, Tirmidhi 3447',
    source: 'Abu Dawood & Tirmidhi',
    benefits: 'Recite when mounting or beginning travel',
    occasion: 'When departing for travel',
  },
  {
    id: 'mosque_1',
    category: 'mosque',
    title: 'Entering the Mosque',
    arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    transliteration: 'Allahumma iftah li abwaba rahmatik',
    translation: 'O Allah, open the gates of Your mercy for me.',
    reference: 'Sahih Muslim 713',
    source: 'Sahih Muslim',
    benefits: 'Said upon entering the mosque',
    occasion: 'Entering mosque',
  },
  {
    id: 'mosque_2',
    category: 'mosque',
    title: 'Leaving the Mosque',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    transliteration: 'Allahumma inni asaluka min fadlik',
    translation: 'O Allah, I ask You from Your bounty.',
    reference: 'Sahih Muslim 713',
    source: 'Sahih Muslim',
    benefits: 'Said upon leaving the mosque',
    occasion: 'Leaving mosque',
  },
  {
    id: 'forgiveness_1',
    category: 'forgiveness',
    title: 'Seeking Forgiveness - Sayyid al-Istighfar',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ',
    transliteration: 'Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana abduka',
    translation: 'O Allah, You are my Lord. There is none worthy of worship but You. You created me and I am your slave.',
    reference: 'Sahih al-Bukhari 6306',
    source: 'Sahih al-Bukhari',
    benefits: 'Master supplication for seeking forgiveness',
    occasion: 'Any time, especially morning and evening',
  },
  {
    id: 'forgiveness_2',
    category: 'forgiveness',
    title: 'Short Istighfar',
    arabic: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ',
    transliteration: 'Astaghfirullaha al-azeemal-ladhi la ilaha illa huwal-hayyul-qayyumu wa atubu ilayh',
    translation: 'I seek forgiveness from Allah the Magnificent, besides Whom none has the right to be worshipped except Him, the Ever-Living, the Self-Subsisting, and I repent to Him.',
    reference: 'Abu Dawood 1517, Tirmidhi 3577',
    source: 'Abu Dawood',
    benefits: 'Allah will forgive sins even if they are like the foam of the sea',
    occasion: 'Any time',
  },
  {
    id: 'illness_1',
    category: 'illness',
    title: 'Dua for the Sick',
    arabic: 'اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ وَاشْفِ أَنْتَ الشَّافِي لَا شِفَاءَ إِلَّا شِفَاؤُكَ شِفَاءً لَا يُغَادِرُ سَقَمًا',
    transliteration: 'Allahumma Rabban-nas, adhhibil-basa washfi, Antash-Shafi, la shifa illa shifa uka, shifaan la yughadiru saqama',
    translation: 'O Allah, Lord of mankind, remove the harm and heal him/her, You are the Healer. There is no healing except Your healing, a healing that leaves no illness.',
    reference: 'Sahih al-Bukhari 5675, Sahih Muslim 2191',
    source: 'Sahih al-Bukhari & Muslim',
    benefits: 'Recite when visiting the sick or for yourself when ill',
    occasion: 'For illness',
  },
  {
    id: 'anxiety_1',
    category: 'anxiety',
    title: 'Dua for Anxiety and Grief',
    arabic: 'اللَّهُمَّ إِنِّي عَبْدُكَ، ابْنُ عَبْدِكَ، ابْنُ أَمَتِكَ، نَاصِيَتِي بِيَدِكَ، مَاضٍ فِيَّ حُكْمُكَ، عَدْلٌ فِيَّ قَضَاؤُكَ',
    transliteration: 'Allahumma inni abduka, ibnu abdika, ibnu amatika, nasiyati biyadika, madin fiyya hukmuka, adlun fiyya qadauka',
    translation: 'O Allah, I am Your servant, son of Your servant, son of Your maidservant, my forelock is in Your hand, Your command over me is forever executed, and Your decree over me is just.',
    reference: 'Ahmad 3712, Ibn Hibban 972',
    source: 'Musnad Ahmad',
    benefits: 'Allah will replace grief with joy',
    occasion: 'When feeling anxious or sad',
  },
  {
    id: 'knowledge_1',
    category: 'knowledge',
    title: 'Dua for Knowledge',
    arabic: 'رَّبِّ زِدْنِي عِلْمًا',
    transliteration: 'Rabbi zidni ilma',
    translation: 'My Lord, increase me in knowledge.',
    reference: 'Quran 20:114',
    source: 'Al-Quran al-Kareem',
    benefits: 'A Quranic dua for increase in knowledge',
    occasion: 'Before studying or seeking knowledge',
  },
  {
    id: 'quran_1',
    category: 'quran',
    title: 'Dua of Ibrahim - Seeking Guidance',
    arabic: 'رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Rabbana taqabbal minna innaka antas-samiul-alim',
    translation: 'Our Lord, accept this from us. Indeed You are the All-Hearing, the All-Knowing.',
    reference: 'Quran 2:127',
    source: 'Al-Quran al-Kareem',
    benefits: 'Dua of Ibrahim when building the Kaaba',
    occasion: 'After performing acts of worship',
  },
  {
    id: 'quran_2',
    category: 'quran',
    title: 'Dua for Guidance on the Straight Path',
    arabic: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ',
    transliteration: 'Ihdinas-siratal-mustaqim',
    translation: 'Guide us to the straight path.',
    reference: 'Quran 1:6',
    source: 'Al-Quran al-Kareem - Surah Al-Fatihah',
    benefits: 'The essence of Al-Fatihah - repeated in every rakah of prayer',
    occasion: 'Daily in prayers',
  },
  {
    id: 'protection_1',
    category: 'protection',
    title: 'Ayat al-Kursi for Protection',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ',
    transliteration: 'Allahu la ilaha illa huwa al-hayyul-qayyum, la takhudhuhhu sinatun wa la nawm',
    translation: 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep.',
    reference: 'Quran 2:255 | Sahih al-Bukhari 2311',
    source: 'Al-Quran al-Kareem',
    benefits: 'Whoever recites this after every obligatory prayer, nothing will prevent him from entering Paradise but death',
    occasion: 'After every prayer, morning and evening',
  },
  {
    id: 'parents_1',
    category: 'parents',
    title: 'Dua for Parents',
    arabic: 'رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    transliteration: 'Rabbir hamhuma kama rabbayanee sagheera',
    translation: 'My Lord, have mercy upon them as they brought me up when I was small.',
    reference: 'Quran 17:24',
    source: 'Al-Quran al-Kareem',
    benefits: 'Quranic dua ordained for children to make for their parents',
    occasion: 'Daily, especially for elderly or deceased parents',
  },
  {
    id: 'istikhara_1',
    category: 'istikhara',
    title: 'Dua al-Istikhara',
    arabic: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ وَتَعْلَمُ وَلَا أَعْلَمُ وَأَنْتَ عَلَّامُ الْغُيُوبِ',
    transliteration: 'Allahumma inni astakhiruka biilmika, wa astaqdiruka biqudratika, wa asaluka min fadlikal-azim, fa innaka taqdiru wa la aqdiru, wa talamu wa la alamu, wa anta allamul-ghuyub',
    translation: 'O Allah, I seek Your counsel by Your knowledge and by Your power I seek strength, and I ask You from Your immense favor, for verily You are able while I am not and verily You know while I do not and You are the Knower of the unseen.',
    reference: 'Sahih al-Bukhari 6382',
    source: 'Sahih al-Bukhari',
    benefits: 'Prayed when making an important decision after 2 rakats of nafl prayer',
    occasion: 'When making an important decision',
  },
  {
    id: 'ramadan_1',
    category: 'ramadan',
    title: 'Dua upon Sighting the Moon',
    arabic: 'اللَّهُمَّ أَهِلَّهُ عَلَيْنَا بِالْيُمْنِ وَالْإِيمَانِ، وَالسَّلَامَةِ وَالْإِسْلَامِ، رَبِّي وَرَبُّكَ اللَّهُ',
    transliteration: 'Allahumma ahillahu alayna bil-yumni wal-iman, was-salamati wal-islam, rabbi wa rabbukallah',
    translation: 'O Allah, bring it over us with blessing and faith, and security and Islam. My Lord and your Lord is Allah.',
    reference: 'Tirmidhi 3451, Ahmad 1397',
    source: 'Tirmidhi',
    benefits: 'Recited upon sighting the new moon for Ramadan or any month',
    occasion: 'Sighting of new moon',
  },
  {
    id: 'general_1',
    category: 'general',
    title: 'Dua for All Good',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: 'Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina adhaban-nar',
    translation: 'Our Lord, give us in this world that which is good and in the Hereafter that which is good and protect us from the torment of the Fire.',
    reference: 'Quran 2:201 | Sahih al-Bukhari 4522',
    source: 'Al-Quran al-Kareem',
    benefits: 'Most comprehensive dua encompassing all good of both worlds',
    occasion: 'Any time',
  },
];
