export interface SurahMeta {
  number: number;
  arabicName: string;
  englishName: string;
  transliteration: string;
  revelationType: 'Meccan' | 'Medinan';
  versesCount: number;
  juzStart: number;
  pages: [number, number];
  meaning: string;
}

export const SURAH_LIST: SurahMeta[] = [
  { number: 1, arabicName: 'الفاتحة', englishName: 'The Opening', transliteration: 'Al-Fatihah', revelationType: 'Meccan', versesCount: 7, juzStart: 1, pages: [1, 1], meaning: 'The Opening' },
  { number: 2, arabicName: 'البقرة', englishName: 'The Cow', transliteration: 'Al-Baqarah', revelationType: 'Medinan', versesCount: 286, juzStart: 1, pages: [2, 49], meaning: 'The Cow' },
  { number: 3, arabicName: 'آل عمران', englishName: 'Family of Imran', transliteration: 'Ali Imran', revelationType: 'Medinan', versesCount: 200, juzStart: 3, pages: [50, 76], meaning: 'Family of Imran' },
  { number: 4, arabicName: 'النساء', englishName: 'The Women', transliteration: 'An-Nisa', revelationType: 'Medinan', versesCount: 176, juzStart: 4, pages: [77, 106], meaning: 'The Women' },
  { number: 5, arabicName: 'المائدة', englishName: 'The Table Spread', transliteration: 'Al-Maidah', revelationType: 'Medinan', versesCount: 120, juzStart: 6, pages: [106, 127], meaning: 'The Table Spread' },
  { number: 6, arabicName: 'الأنعام', englishName: 'The Cattle', transliteration: 'Al-Anam', revelationType: 'Meccan', versesCount: 165, juzStart: 7, pages: [128, 150], meaning: 'The Cattle' },
  { number: 7, arabicName: 'الأعراف', englishName: 'The Heights', transliteration: 'Al-Araf', revelationType: 'Meccan', versesCount: 206, juzStart: 8, pages: [151, 176], meaning: 'The Heights' },
  { number: 8, arabicName: 'الأنفال', englishName: 'The Spoils of War', transliteration: 'Al-Anfal', revelationType: 'Medinan', versesCount: 75, juzStart: 9, pages: [177, 186], meaning: 'The Spoils of War' },
  { number: 9, arabicName: 'التوبة', englishName: 'The Repentance', transliteration: 'At-Tawbah', revelationType: 'Medinan', versesCount: 129, juzStart: 10, pages: [187, 207], meaning: 'The Repentance' },
  { number: 10, arabicName: 'يونس', englishName: 'Jonah', transliteration: 'Yunus', revelationType: 'Meccan', versesCount: 109, juzStart: 11, pages: [208, 221], meaning: 'Jonah' },
  { number: 11, arabicName: 'هود', englishName: 'Hud', transliteration: 'Hud', revelationType: 'Meccan', versesCount: 123, juzStart: 11, pages: [221, 235], meaning: 'Hud' },
  { number: 12, arabicName: 'يوسف', englishName: 'Joseph', transliteration: 'Yusuf', revelationType: 'Meccan', versesCount: 111, juzStart: 12, pages: [235, 248], meaning: 'Joseph' },
  { number: 13, arabicName: 'الرعد', englishName: 'The Thunder', transliteration: 'Ar-Rad', revelationType: 'Medinan', versesCount: 43, juzStart: 13, pages: [249, 255], meaning: 'The Thunder' },
  { number: 14, arabicName: 'إبراهيم', englishName: 'Ibrahim', transliteration: 'Ibrahim', revelationType: 'Meccan', versesCount: 52, juzStart: 13, pages: [255, 261], meaning: 'Ibrahim' },
  { number: 15, arabicName: 'الحجر', englishName: 'The Rocky Tract', transliteration: 'Al-Hijr', revelationType: 'Meccan', versesCount: 99, juzStart: 14, pages: [262, 267], meaning: 'The Rocky Tract' },
  { number: 16, arabicName: 'النحل', englishName: 'The Bee', transliteration: 'An-Nahl', revelationType: 'Meccan', versesCount: 128, juzStart: 14, pages: [267, 281], meaning: 'The Bee' },
  { number: 17, arabicName: 'الإسراء', englishName: 'The Night Journey', transliteration: 'Al-Isra', revelationType: 'Meccan', versesCount: 111, juzStart: 15, pages: [282, 293], meaning: 'The Night Journey' },
  { number: 18, arabicName: 'الكهف', englishName: 'The Cave', transliteration: 'Al-Kahf', revelationType: 'Meccan', versesCount: 110, juzStart: 15, pages: [293, 304], meaning: 'The Cave' },
  { number: 19, arabicName: 'مريم', englishName: 'Mary', transliteration: 'Maryam', revelationType: 'Meccan', versesCount: 98, juzStart: 16, pages: [305, 312], meaning: 'Mary' },
  { number: 20, arabicName: 'طه', englishName: 'Ta-Ha', transliteration: 'Ta-Ha', revelationType: 'Meccan', versesCount: 135, juzStart: 16, pages: [312, 321], meaning: 'Ta-Ha' },
  { number: 21, arabicName: 'الأنبياء', englishName: 'The Prophets', transliteration: 'Al-Anbiya', revelationType: 'Meccan', versesCount: 112, juzStart: 17, pages: [322, 331], meaning: 'The Prophets' },
  { number: 22, arabicName: 'الحج', englishName: 'The Pilgrimage', transliteration: 'Al-Hajj', revelationType: 'Medinan', versesCount: 78, juzStart: 17, pages: [332, 341], meaning: 'The Pilgrimage' },
  { number: 23, arabicName: 'المؤمنون', englishName: 'The Believers', transliteration: 'Al-Muminun', revelationType: 'Meccan', versesCount: 118, juzStart: 18, pages: [342, 349], meaning: 'The Believers' },
  { number: 24, arabicName: 'النور', englishName: 'The Light', transliteration: 'An-Nur', revelationType: 'Medinan', versesCount: 64, juzStart: 18, pages: [350, 359], meaning: 'The Light' },
  { number: 25, arabicName: 'الفرقان', englishName: 'The Criterion', transliteration: 'Al-Furqan', revelationType: 'Meccan', versesCount: 77, juzStart: 18, pages: [359, 366], meaning: 'The Criterion' },
  { number: 26, arabicName: 'الشعراء', englishName: 'The Poets', transliteration: 'Ash-Shuara', revelationType: 'Meccan', versesCount: 227, juzStart: 19, pages: [367, 376], meaning: 'The Poets' },
  { number: 27, arabicName: 'النمل', englishName: 'The Ant', transliteration: 'An-Naml', revelationType: 'Meccan', versesCount: 93, juzStart: 19, pages: [377, 385], meaning: 'The Ant' },
  { number: 28, arabicName: 'القصص', englishName: 'The Stories', transliteration: 'Al-Qasas', revelationType: 'Meccan', versesCount: 88, juzStart: 20, pages: [385, 396], meaning: 'The Stories' },
  { number: 29, arabicName: 'العنكبوت', englishName: 'The Spider', transliteration: 'Al-Ankabut', revelationType: 'Meccan', versesCount: 69, juzStart: 20, pages: [396, 404], meaning: 'The Spider' },
  { number: 30, arabicName: 'الروم', englishName: 'The Romans', transliteration: 'Ar-Rum', revelationType: 'Meccan', versesCount: 60, juzStart: 21, pages: [404, 410], meaning: 'The Romans' },
  { number: 31, arabicName: 'لقمان', englishName: 'Luqman', transliteration: 'Luqman', revelationType: 'Meccan', versesCount: 34, juzStart: 21, pages: [411, 414], meaning: 'Luqman' },
  { number: 32, arabicName: 'السجدة', englishName: 'The Prostration', transliteration: 'As-Sajdah', revelationType: 'Meccan', versesCount: 30, juzStart: 21, pages: [415, 417], meaning: 'The Prostration' },
  { number: 33, arabicName: 'الأحزاب', englishName: 'The Combined Forces', transliteration: 'Al-Ahzab', revelationType: 'Medinan', versesCount: 73, juzStart: 21, pages: [418, 427], meaning: 'The Combined Forces' },
  { number: 34, arabicName: 'سبأ', englishName: 'Sheba', transliteration: 'Saba', revelationType: 'Meccan', versesCount: 54, juzStart: 22, pages: [428, 434], meaning: 'Sheba' },
  { number: 35, arabicName: 'فاطر', englishName: 'Originator', transliteration: 'Fatir', revelationType: 'Meccan', versesCount: 45, juzStart: 22, pages: [434, 440], meaning: 'Originator' },
  { number: 36, arabicName: 'يس', englishName: 'Ya Sin', transliteration: 'Ya-Sin', revelationType: 'Meccan', versesCount: 83, juzStart: 22, pages: [440, 445], meaning: 'Ya Sin' },
  { number: 37, arabicName: 'الصافات', englishName: 'Those Who Set The Ranks', transliteration: 'As-Saffat', revelationType: 'Meccan', versesCount: 182, juzStart: 23, pages: [446, 452], meaning: 'Those Who Set The Ranks' },
  { number: 38, arabicName: 'ص', englishName: 'The Letter Sad', transliteration: 'Sad', revelationType: 'Meccan', versesCount: 88, juzStart: 23, pages: [453, 458], meaning: 'The Letter Sad' },
  { number: 39, arabicName: 'الزمر', englishName: 'The Troops', transliteration: 'Az-Zumar', revelationType: 'Meccan', versesCount: 75, juzStart: 23, pages: [458, 467], meaning: 'The Troops' },
  { number: 40, arabicName: 'غافر', englishName: 'The Forgiver', transliteration: 'Ghafir', revelationType: 'Meccan', versesCount: 85, juzStart: 24, pages: [467, 476], meaning: 'The Forgiver' },
  { number: 41, arabicName: 'فصلت', englishName: 'Explained In Detail', transliteration: 'Fussilat', revelationType: 'Meccan', versesCount: 54, juzStart: 24, pages: [477, 482], meaning: 'Explained In Detail' },
  { number: 42, arabicName: 'الشورى', englishName: 'The Consultation', transliteration: 'Ash-Shura', revelationType: 'Meccan', versesCount: 53, juzStart: 25, pages: [483, 489], meaning: 'The Consultation' },
  { number: 43, arabicName: 'الزخرف', englishName: 'The Ornaments of Gold', transliteration: 'Az-Zukhruf', revelationType: 'Meccan', versesCount: 89, juzStart: 25, pages: [489, 495], meaning: 'The Ornaments of Gold' },
  { number: 44, arabicName: 'الدخان', englishName: 'The Smoke', transliteration: 'Ad-Dukhan', revelationType: 'Meccan', versesCount: 59, juzStart: 25, pages: [496, 498], meaning: 'The Smoke' },
  { number: 45, arabicName: 'الجاثية', englishName: 'The Crouching', transliteration: 'Al-Jathiyah', revelationType: 'Meccan', versesCount: 37, juzStart: 25, pages: [499, 502], meaning: 'The Crouching' },
  { number: 46, arabicName: 'الأحقاف', englishName: 'The Wind-Curved Sandhills', transliteration: 'Al-Ahqaf', revelationType: 'Meccan', versesCount: 35, juzStart: 26, pages: [502, 506], meaning: 'The Wind-Curved Sandhills' },
  { number: 47, arabicName: 'محمد', englishName: 'Muhammad', transliteration: 'Muhammad', revelationType: 'Medinan', versesCount: 38, juzStart: 26, pages: [507, 510], meaning: 'Muhammad' },
  { number: 48, arabicName: 'الفتح', englishName: 'The Victory', transliteration: 'Al-Fath', revelationType: 'Medinan', versesCount: 29, juzStart: 26, pages: [511, 515], meaning: 'The Victory' },
  { number: 49, arabicName: 'الحجرات', englishName: 'The Rooms', transliteration: 'Al-Hujurat', revelationType: 'Medinan', versesCount: 18, juzStart: 26, pages: [515, 517], meaning: 'The Rooms' },
  { number: 50, arabicName: 'ق', englishName: 'The Letter Qaf', transliteration: 'Qaf', revelationType: 'Meccan', versesCount: 45, juzStart: 26, pages: [518, 520], meaning: 'The Letter Qaf' },
  { number: 51, arabicName: 'الذاريات', englishName: 'The Winnowing Winds', transliteration: 'Adh-Dhariyat', revelationType: 'Meccan', versesCount: 60, juzStart: 26, pages: [520, 523], meaning: 'The Winnowing Winds' },
  { number: 52, arabicName: 'الطور', englishName: 'The Mount', transliteration: 'At-Tur', revelationType: 'Meccan', versesCount: 49, juzStart: 27, pages: [523, 525], meaning: 'The Mount' },
  { number: 53, arabicName: 'النجم', englishName: 'The Star', transliteration: 'An-Najm', revelationType: 'Meccan', versesCount: 62, juzStart: 27, pages: [526, 528], meaning: 'The Star' },
  { number: 54, arabicName: 'القمر', englishName: 'The Moon', transliteration: 'Al-Qamar', revelationType: 'Meccan', versesCount: 55, juzStart: 27, pages: [528, 531], meaning: 'The Moon' },
  { number: 55, arabicName: 'الرحمن', englishName: 'The Beneficent', transliteration: 'Ar-Rahman', revelationType: 'Medinan', versesCount: 78, juzStart: 27, pages: [531, 534], meaning: 'The Beneficent' },
  { number: 56, arabicName: 'الواقعة', englishName: 'The Inevitable', transliteration: 'Al-Waqiah', revelationType: 'Meccan', versesCount: 96, juzStart: 27, pages: [534, 537], meaning: 'The Inevitable' },
  { number: 57, arabicName: 'الحديد', englishName: 'The Iron', transliteration: 'Al-Hadid', revelationType: 'Medinan', versesCount: 29, juzStart: 27, pages: [537, 541], meaning: 'The Iron' },
  { number: 58, arabicName: 'المجادلة', englishName: 'She That Disputeth', transliteration: 'Al-Mujadila', revelationType: 'Medinan', versesCount: 22, juzStart: 28, pages: [542, 545], meaning: 'She That Disputeth' },
  { number: 59, arabicName: 'الحشر', englishName: 'The Exile', transliteration: 'Al-Hashr', revelationType: 'Medinan', versesCount: 24, juzStart: 28, pages: [545, 548], meaning: 'The Exile' },
  { number: 60, arabicName: 'الممتحنة', englishName: 'She that is to be examined', transliteration: 'Al-Mumtahanah', revelationType: 'Medinan', versesCount: 13, juzStart: 28, pages: [549, 551], meaning: 'She that is to be examined' },
  { number: 61, arabicName: 'الصف', englishName: 'The Ranks', transliteration: 'As-Saf', revelationType: 'Medinan', versesCount: 14, juzStart: 28, pages: [551, 552], meaning: 'The Ranks' },
  { number: 62, arabicName: 'الجمعة', englishName: 'Friday', transliteration: 'Al-Jumuah', revelationType: 'Medinan', versesCount: 11, juzStart: 28, pages: [553, 554], meaning: 'Friday' },
  { number: 63, arabicName: 'المنافقون', englishName: 'The Hypocrites', transliteration: 'Al-Munafiqun', revelationType: 'Medinan', versesCount: 11, juzStart: 28, pages: [554, 555], meaning: 'The Hypocrites' },
  { number: 64, arabicName: 'التغابن', englishName: 'Mutual Disillusion', transliteration: 'At-Taghabun', revelationType: 'Medinan', versesCount: 18, juzStart: 28, pages: [556, 557], meaning: 'Mutual Disillusion' },
  { number: 65, arabicName: 'الطلاق', englishName: 'Divorce', transliteration: 'At-Talaq', revelationType: 'Medinan', versesCount: 12, juzStart: 28, pages: [558, 559], meaning: 'Divorce' },
  { number: 66, arabicName: 'التحريم', englishName: 'The Prohibition', transliteration: 'At-Tahrim', revelationType: 'Medinan', versesCount: 12, juzStart: 28, pages: [560, 561], meaning: 'The Prohibition' },
  { number: 67, arabicName: 'الملك', englishName: 'The Sovereignty', transliteration: 'Al-Mulk', revelationType: 'Meccan', versesCount: 30, juzStart: 29, pages: [562, 564], meaning: 'The Sovereignty' },
  { number: 68, arabicName: 'القلم', englishName: 'The Pen', transliteration: 'Al-Qalam', revelationType: 'Meccan', versesCount: 52, juzStart: 29, pages: [564, 566], meaning: 'The Pen' },
  { number: 69, arabicName: 'الحاقة', englishName: 'The Reality', transliteration: 'Al-Haqqah', revelationType: 'Meccan', versesCount: 52, juzStart: 29, pages: [566, 568], meaning: 'The Reality' },
  { number: 70, arabicName: 'المعارج', englishName: 'The Ascending Stairways', transliteration: 'Al-Maarij', revelationType: 'Meccan', versesCount: 44, juzStart: 29, pages: [568, 570], meaning: 'The Ascending Stairways' },
  { number: 71, arabicName: 'نوح', englishName: 'Noah', transliteration: 'Nuh', revelationType: 'Meccan', versesCount: 28, juzStart: 29, pages: [570, 571], meaning: 'Noah' },
  { number: 72, arabicName: 'الجن', englishName: 'The Jinn', transliteration: 'Al-Jinn', revelationType: 'Meccan', versesCount: 28, juzStart: 29, pages: [572, 573], meaning: 'The Jinn' },
  { number: 73, arabicName: 'المزمل', englishName: 'The Enshrouded One', transliteration: 'Al-Muzzammil', revelationType: 'Meccan', versesCount: 20, juzStart: 29, pages: [574, 575], meaning: 'The Enshrouded One' },
  { number: 74, arabicName: 'المدثر', englishName: 'The Cloaked One', transliteration: 'Al-Muddaththir', revelationType: 'Meccan', versesCount: 56, juzStart: 29, pages: [575, 577], meaning: 'The Cloaked One' },
  { number: 75, arabicName: 'القيامة', englishName: 'The Resurrection', transliteration: 'Al-Qiyamah', revelationType: 'Meccan', versesCount: 40, juzStart: 29, pages: [577, 578], meaning: 'The Resurrection' },
  { number: 76, arabicName: 'الإنسان', englishName: 'The Man', transliteration: 'Al-Insan', revelationType: 'Medinan', versesCount: 31, juzStart: 29, pages: [578, 580], meaning: 'The Man' },
  { number: 77, arabicName: 'المرسلات', englishName: 'The Emissaries', transliteration: 'Al-Mursalat', revelationType: 'Meccan', versesCount: 50, juzStart: 29, pages: [580, 581], meaning: 'The Emissaries' },
  { number: 78, arabicName: 'النبأ', englishName: 'The Announcement', transliteration: 'An-Naba', revelationType: 'Meccan', versesCount: 40, juzStart: 30, pages: [582, 583], meaning: 'The Announcement' },
  { number: 79, arabicName: 'النازعات', englishName: 'Those who drag forth', transliteration: 'An-Naziat', revelationType: 'Meccan', versesCount: 46, juzStart: 30, pages: [583, 584], meaning: 'Those who drag forth' },
  { number: 80, arabicName: 'عبس', englishName: 'He Frowned', transliteration: 'Abasa', revelationType: 'Meccan', versesCount: 42, juzStart: 30, pages: [585, 585], meaning: 'He Frowned' },
  { number: 81, arabicName: 'التكوير', englishName: 'The Overthrowing', transliteration: 'At-Takwir', revelationType: 'Meccan', versesCount: 29, juzStart: 30, pages: [586, 586], meaning: 'The Overthrowing' },
  { number: 82, arabicName: 'الانفطار', englishName: 'The Cleaving', transliteration: 'Al-Infitar', revelationType: 'Meccan', versesCount: 19, juzStart: 30, pages: [587, 587], meaning: 'The Cleaving' },
  { number: 83, arabicName: 'المطففين', englishName: 'The Defrauding', transliteration: 'Al-Mutaffifin', revelationType: 'Meccan', versesCount: 36, juzStart: 30, pages: [587, 589], meaning: 'The Defrauding' },
  { number: 84, arabicName: 'الانشقاق', englishName: 'The Splitting Open', transliteration: 'Al-Inshiqaq', revelationType: 'Meccan', versesCount: 25, juzStart: 30, pages: [589, 589], meaning: 'The Splitting Open' },
  { number: 85, arabicName: 'البروج', englishName: 'The Mansions of the Stars', transliteration: 'Al-Buruj', revelationType: 'Meccan', versesCount: 22, juzStart: 30, pages: [590, 590], meaning: 'The Mansions of the Stars' },
  { number: 86, arabicName: 'الطارق', englishName: 'The Nightcommer', transliteration: 'At-Tariq', revelationType: 'Meccan', versesCount: 17, juzStart: 30, pages: [591, 591], meaning: 'The Nightcommer' },
  { number: 87, arabicName: 'الأعلى', englishName: 'The Most High', transliteration: 'Al-Ala', revelationType: 'Meccan', versesCount: 19, juzStart: 30, pages: [591, 591], meaning: 'The Most High' },
  { number: 88, arabicName: 'الغاشية', englishName: 'The Overwhelming', transliteration: 'Al-Ghashiyah', revelationType: 'Meccan', versesCount: 26, juzStart: 30, pages: [592, 592], meaning: 'The Overwhelming' },
  { number: 89, arabicName: 'الفجر', englishName: 'The Dawn', transliteration: 'Al-Fajr', revelationType: 'Meccan', versesCount: 30, juzStart: 30, pages: [593, 594], meaning: 'The Dawn' },
  { number: 90, arabicName: 'البلد', englishName: 'The City', transliteration: 'Al-Balad', revelationType: 'Meccan', versesCount: 20, juzStart: 30, pages: [594, 594], meaning: 'The City' },
  { number: 91, arabicName: 'الشمس', englishName: 'The Sun', transliteration: 'Ash-Shams', revelationType: 'Meccan', versesCount: 15, juzStart: 30, pages: [595, 595], meaning: 'The Sun' },
  { number: 92, arabicName: 'الليل', englishName: 'The Night', transliteration: 'Al-Layl', revelationType: 'Meccan', versesCount: 21, juzStart: 30, pages: [595, 596], meaning: 'The Night' },
  { number: 93, arabicName: 'الضحى', englishName: 'The Morning Hours', transliteration: 'Ad-Duha', revelationType: 'Meccan', versesCount: 11, juzStart: 30, pages: [596, 596], meaning: 'The Morning Hours' },
  { number: 94, arabicName: 'الشرح', englishName: 'The Relief', transliteration: 'Ash-Sharh', revelationType: 'Meccan', versesCount: 8, juzStart: 30, pages: [596, 596], meaning: 'The Relief' },
  { number: 95, arabicName: 'التين', englishName: 'The Fig', transliteration: 'At-Tin', revelationType: 'Meccan', versesCount: 8, juzStart: 30, pages: [597, 597], meaning: 'The Fig' },
  { number: 96, arabicName: 'العلق', englishName: 'The Clot', transliteration: 'Al-Alaq', revelationType: 'Meccan', versesCount: 19, juzStart: 30, pages: [597, 598], meaning: 'The Clot' },
  { number: 97, arabicName: 'القدر', englishName: 'The Power', transliteration: 'Al-Qadr', revelationType: 'Meccan', versesCount: 5, juzStart: 30, pages: [598, 598], meaning: 'The Power' },
  { number: 98, arabicName: 'البينة', englishName: 'The Clear Proof', transliteration: 'Al-Bayyinah', revelationType: 'Medinan', versesCount: 8, juzStart: 30, pages: [598, 599], meaning: 'The Clear Proof' },
  { number: 99, arabicName: 'الزلزلة', englishName: 'The Earthquake', transliteration: 'Az-Zalzalah', revelationType: 'Medinan', versesCount: 8, juzStart: 30, pages: [599, 599], meaning: 'The Earthquake' },
  { number: 100, arabicName: 'العاديات', englishName: 'The Courser', transliteration: 'Al-Adiyat', revelationType: 'Meccan', versesCount: 11, juzStart: 30, pages: [599, 600], meaning: 'The Courser' },
  { number: 101, arabicName: 'القارعة', englishName: 'The Calamity', transliteration: 'Al-Qariah', revelationType: 'Meccan', versesCount: 11, juzStart: 30, pages: [600, 600], meaning: 'The Calamity' },
  { number: 102, arabicName: 'التكاثر', englishName: 'The Rivalry in World Increase', transliteration: 'At-Takathur', revelationType: 'Meccan', versesCount: 8, juzStart: 30, pages: [600, 600], meaning: 'The Rivalry in World Increase' },
  { number: 103, arabicName: 'العصر', englishName: 'The Declining Day', transliteration: 'Al-Asr', revelationType: 'Meccan', versesCount: 3, juzStart: 30, pages: [601, 601], meaning: 'The Declining Day' },
  { number: 104, arabicName: 'الهمزة', englishName: 'The Traducer', transliteration: 'Al-Humazah', revelationType: 'Meccan', versesCount: 9, juzStart: 30, pages: [601, 601], meaning: 'The Traducer' },
  { number: 105, arabicName: 'الفيل', englishName: 'The Elephant', transliteration: 'Al-Fil', revelationType: 'Meccan', versesCount: 5, juzStart: 30, pages: [601, 601], meaning: 'The Elephant' },
  { number: 106, arabicName: 'قريش', englishName: 'Quraysh', transliteration: 'Quraysh', revelationType: 'Meccan', versesCount: 4, juzStart: 30, pages: [602, 602], meaning: 'Quraysh' },
  { number: 107, arabicName: 'الماعون', englishName: 'The Small Kindnesses', transliteration: 'Al-Maun', revelationType: 'Meccan', versesCount: 7, juzStart: 30, pages: [602, 602], meaning: 'The Small Kindnesses' },
  { number: 108, arabicName: 'الكوثر', englishName: 'The Abundance', transliteration: 'Al-Kawthar', revelationType: 'Meccan', versesCount: 3, juzStart: 30, pages: [602, 602], meaning: 'The Abundance' },
  { number: 109, arabicName: 'الكافرون', englishName: 'The Disbelievers', transliteration: 'Al-Kafirun', revelationType: 'Meccan', versesCount: 6, juzStart: 30, pages: [603, 603], meaning: 'The Disbelievers' },
  { number: 110, arabicName: 'النصر', englishName: 'The Divine Support', transliteration: 'An-Nasr', revelationType: 'Medinan', versesCount: 3, juzStart: 30, pages: [603, 603], meaning: 'The Divine Support' },
  { number: 111, arabicName: 'المسد', englishName: 'The Palm Fibre', transliteration: 'Al-Masad', revelationType: 'Meccan', versesCount: 5, juzStart: 30, pages: [603, 603], meaning: 'The Palm Fibre' },
  { number: 112, arabicName: 'الإخلاص', englishName: 'The Sincerity', transliteration: 'Al-Ikhlas', revelationType: 'Meccan', versesCount: 4, juzStart: 30, pages: [604, 604], meaning: 'The Sincerity' },
  { number: 113, arabicName: 'الفلق', englishName: 'The Daybreak', transliteration: 'Al-Falaq', revelationType: 'Meccan', versesCount: 5, juzStart: 30, pages: [604, 604], meaning: 'The Daybreak' },
  { number: 114, arabicName: 'الناس', englishName: 'Mankind', transliteration: 'An-Nas', revelationType: 'Meccan', versesCount: 6, juzStart: 30, pages: [604, 604], meaning: 'Mankind' },
];

export const RECITERS = [
  { id: 'ar.alafasy', name: 'Mishary Rashid Alafasy', arabicName: 'مشاري راشد العفاسي', style: 'Murattal', identifier: 'Alafasy_128kbps' },
  { id: 'ar.abdurrahmaansudais', name: 'Abdul Rahman Al-Sudais', arabicName: 'عبدالرحمن السديس', style: 'Murattal', identifier: 'Sudais_128kbps' },
  { id: 'ar.mahermuaiqly', name: 'Maher Al-Muaiqly', arabicName: 'ماهر المعيقلي', style: 'Murattal', identifier: 'MaherAlMuaiqly128kbps' },
  { id: 'ar.minshawi', name: 'Muhammad Siddiq Al-Minshawi', arabicName: 'محمد صديق المنشاوي', style: 'Murattal', identifier: 'Minshawy_Murattal_128kbps' },
  { id: 'ar.husary', name: 'Mahmoud Khalil Al-Husary', arabicName: 'محمود خليل الحصري', style: 'Murattal', identifier: 'Husary_128kbps' },
  { id: 'ar.ahmedajamy', name: 'Ahmed Al-Ajmy', arabicName: 'أحمد العجمي', style: 'Murattal', identifier: 'Ahmed_ibn_Ali_al-Ajamy_128kbps_ketaballah.net' },
  { id: 'ar.saoodshuraym', name: 'Saud Al-Shuraim', arabicName: 'سعود الشريم', style: 'Murattal', identifier: 'Shuraym_128kbps' },
];

export const TRANSLATIONS = [
  { id: 'en.sahih', name: 'Sahih International', language: 'English', flag: '🇬🇧' },
  { id: 'en.pickthall', name: 'Pickthall', language: 'English', flag: '🇬🇧' },
  { id: 'en.yusufali', name: 'Yusuf Ali', language: 'English', flag: '🇬🇧' },
  { id: 'ur.jalandhry', name: 'Jalandhry', language: 'Urdu', flag: '🇵🇰' },
  { id: 'ur.ahmedali', name: 'Ahmed Ali', language: 'Urdu', flag: '🇵🇰' },
  { id: 'fr.hamidullah', name: 'Hamidullah', language: 'French', flag: '🇫🇷' },
  { id: 'de.aburida', name: 'Abu Rida', language: 'German', flag: '🇩🇪' },
  { id: 'tr.diyanet', name: 'Diyanet', language: 'Turkish', flag: '🇹🇷' },
  { id: 'id.indonesian', name: 'Indonesian Ministry', language: 'Indonesian', flag: '🇮🇩' },
];

export const JUZ_LIST = Array.from({ length: 30 }, (_, i) => ({
  number: i + 1,
  name: `Juz ${i + 1}`,
  arabicName: `الجزء ${i + 1}`,
}));
